# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.
    - 원본 배열을 변경시키지 않는다. (shape를 바꾼 새로운 배열(카피본)을 반환)

In [8]:
import numpy as np
a = np.arange(20)
print(a.shape, a.size)
print(a,end='\n\n')

b = np.reshape(a, (4,5))
print(b.shape, b.size)
print(b,end='\n\n')

c = a.reshape((5,4))
print(c.shape, c.size)
print(c,end='\n\n')

d = np.arange(3*2*7).reshape(3,2,7)
print(d,end='\n\n')

e = np.reshape(d, 42) # newshape에 정수를 넣으면 1차원 배열로 변환
print(e,end='\n\n')

(20,) 20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

(4, 5) 20
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

(5, 4) 20
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]



- newshape을 지정할 때 특정 축에 -1를 주면 원소수에 맞춰서 size를 정한다.(전체 축 중 하나만 사용가능)

In [9]:
a_1 = np.reshape(a, (5,-1)) # 5 x ? = 20
print(a_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## 차원 늘리기(확장)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 축(axis)을 추가할 때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    

In [11]:
import numpy as np
a = np.arange(1,6)
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [27]:
# (5,) => (1, 5)
x = a[np.newaxis, :]
print(x.shape)
print(x,end='\n\n')

# a: (5,) => y: (5, 1)
y = a[:, np.newaxis]
print(y.shape)
print(y)

# a: (5, ) => z: (1, 5, 1)
z = a[np.newaxis, :, np.newaxis]
print(z.shape)
print(z)

b = np.arange(6).reshape(2,3)
print(b.shape)
print(b)
# b: (2,3) => m: (1,2,3)
m = b[np.newaxis, :, :]
print(m.shape)
print(m)

n = b[:, np.newaxis, :]
print(n.shape)
print(n)

(1, 5)
[[1 2 3 4 5]]

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]
(1, 5, 1)
[[[1]
  [2]
  [3]
  [4]
  [5]]]
(2, 3)
[[0 1 2]
 [3 4 5]]
(1, 2, 3)
[[[0 1 2]
  [3 4 5]]]
(2, 1, 3)
[[[0 1 2]]

 [[3 4 5]]]


### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [28]:
b2 = b[np.newaxis, ...]
print(b2.shape)
print(b2)

b3 = b[..., np.newaxis]
print(b3.shape)
print(b3)

(1, 2, 3)
[[[0 1 2]
  [3 4 5]]]
(2, 3, 1)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]


### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.

In [32]:
print(a.shape)
print(a, end='\n\n')

# (5,) -> (5,1)
a1 = np.expand_dims(a, axis=1)
print(a1.shape)
print(a1, end='\n\n')

# (5,) -> (1,5)
a2 = np.expand_dims(a, axis=0)
print(a2.shape)
print(a2)

(5,)
[1 2 3 4 5]

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]

(1, 5)
[[1 2 3 4 5]]


## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [37]:
a = np.arange(12).reshape(1,2,1,2,3,1)
print(a.shape)

b = np.squeeze(a)
print(b.shape)

c = np.squeeze(a, axis=2)
print(c.shape)
print(c)

(1, 2, 1, 2, 3, 1)
(2, 2, 3)
(1, 2, 2, 3, 1)
[[[[[ 0]
    [ 1]
    [ 2]]

   [[ 3]
    [ 4]
    [ 5]]]


  [[[ 6]
    [ 7]
    [ 8]]

   [[ 9]
    [10]
    [11]]]]]


### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [41]:
# (2,3) => (6,)
# (2,2,2,3) -> (24,)
d = a.flatten()
print(d.shape)
print(d)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [44]:
import numpy as np

a = np.array([1,2,3])
r = np.append(a, 100) # 1개의 값을 추가
print(r)
r = np.append(a, [200,300,400]) # 여러 개 값 동시에 추가시 리스트로 묶어 전달
print(r)

[  1   2   3 100]
[  1   2   3 200 300 400]


In [52]:
l = [
    [1,1],
    [2,2],
    [3,3]
]
b = np.array(l)
print(b.shape)
print(b)

r1 = np.append(b, [[4,4]], axis=0)
print(r1.shape)
print(r1)

r2 = np.append(b, [[4,4],[5,5],[6,6]], axis=0)
print(r2.shape)
print(r2)

r3 = np.append(b, [[1],[2],[3]], axis=1)
print(r3.shape)
print(r3)

r4 = np.append(b, [[4,4,4],[5,5,5],[6,6,6]], axis=1)
print(r4.shape)
print(r4)

r5 = np.append(b, [10,20]) # 다차원배열에서 axis 생략 -> flatten() 후에 append()
print(r5.shape)
print(r5)

(3, 2)
[[1 1]
 [2 2]
 [3 3]]
(4, 2)
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
(6, 2)
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]
(3, 3)
[[1 1 1]
 [2 2 2]
 [3 3 3]]
(3, 5)
[[1 1 4 4 4]
 [2 2 5 5 5]
 [3 3 6 6 6]]
(8,)
[ 1  1  2  2  3  3 10 20]


### insert

In [64]:
a = np.array([1,2,3])
print(a)

r = np.insert(a, 0, 100) # index 0에 100을 삽입
print(r)

r1 = np.insert(a, 2, 200)
print(r1)

r2 = np.insert(a, 1, [10,20,30])
print(r2)

b = np.array([[1,1],[2,2],[3,3]])
print(b)

b1 = np.insert(b, 1, 100) # axis 생략시에는 무조건 faltten(), 그리고 뒤에 insert()
print(b1)

b2 = np.insert(b, 1, [10,10], axis=0)
print(b2)

b3 = np.insert(b, 1, [[10,10],[20,20]], axis=0)
print(b3)

b4 = np.insert(b, 2, 100, axis=0) # 동일한 값을 넣을 경우 정수 하나(스칼라값)을 넣어서도 가능
print(b4)

b5 = np.insert(b, 1, [10,20,30], axis=1)
print(b5)

b6 = np.insert(b, 1, [[10,20,30],[5,6,7]], axis=1)
print(b6)

[1 2 3]
[100   1   2   3]
[  1   2 200   3]
[ 1 10 20 30  2  3]
[[1 1]
 [2 2]
 [3 3]]
[  1 100   1   2   2   3   3]
[[ 1  1]
 [10 10]
 [ 2  2]
 [ 3  3]]
[[ 1  1]
 [10 10]
 [20 20]
 [ 2  2]
 [ 3  3]]
[[  1   1]
 [  2   2]
 [100 100]
 [  3   3]]
[[ 1 10  1]
 [ 2 20  2]
 [ 3 30  3]]
[[ 1 10  5  1]
 [ 2 20  6  2]
 [ 3 30  7  3]]


### delete

In [66]:
a = np.arange(10)
print(a)

r = np.delete(a,0)
print(r)

r1 = np.delete(a, [2,5,6])
print(r1)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 1 3 4 7 8 9]


In [69]:
# slicing을 이용해서 삭제
# numpy상에서의 slicing 표기법, slicing을 함수의 매개변수로 전달할 경우
# np.s_[slicing]
r2 = np.delete(a, np.s_[::2])
print(r2)

[1 3 5 7 9]


In [74]:
b = np.arange(36).reshape(6,6)
print(b.shape)
print(b)
print(np.delete(b,[0,1],axis=0))
print(np.delete(b,[0,1],axis=1))
print(np.delete(b,0)) # axis 생략: flatten() 후에 delete()

(6, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]
 [32 33 34 35]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의 개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ##### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
    - ##### vstack(합칠 배열리스트)
        - 수직으로 쌓는다.
        - concatenate() 의 axis=0 와 동일
        - 합칠 배열들의 열수가 같아야 한다.
    - ##### hstack(합칠 배열리스트)
        - 수평으로 쌓는다.
        - concatenate() 의 axis=1 와 동일
        - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

In [76]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30,40])
c = np.array([100,200])

# 1차원 배열 합치기
d = np.concatenate([a,b])
print(d)

e = np.concatenate([b,a])
print(e)

f = np.concatenate([a,b,c])
print(f)

[ 1  2  3 10 20 30 40]
[10 20 30 40  1  2  3]
[  1   2   3  10  20  30  40 100 200]


In [78]:
m = np.arange(6).reshape(2,3)
n = np.arange(10,16).reshape(2,3)
o = np.arange(20,26).reshape(2,3)
print(m.shape, n.shape, o.shape)

(2, 3) (2, 3) (2, 3)


In [84]:
r = np.concatenate([m,n], axis=0)
print(r.shape)
print(r)

s = np.concatenate([m,n,o], axis=1)
print(s.shape)
print(s)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
(2, 9)
[[ 0  1  2 10 11 12 20 21 22]
 [ 3  4  5 13 14 15 23 24 25]]


In [85]:
a = np.arange(12).reshape(2,2,3)
b = np.arange(2*2*7).reshape(2,2,7)
r = np.concatenate([a,b], axis=2)
print(a.shape, b.shape, r.shape)
print(r)

(2, 2, 3) (2, 2, 7) (2, 2, 10)
[[[ 0  1  2  0  1  2  3  4  5  6]
  [ 3  4  5  7  8  9 10 11 12 13]]

 [[ 6  7  8 14 15 16 17 18 19 20]
  [ 9 10 11 21 22 23 24 25 26 27]]]


### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [86]:
m.shape, n.shape, o.shape

((2, 3), (2, 3), (2, 3))

In [90]:
print(np.vstack([m,n]))
print(np.vstack([m,o,n]))
# 1축의 개수가 같아야 한다.

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [20 21 22]
 [23 24 25]
 [10 11 12]
 [13 14 15]]


### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

In [92]:
print(np.hstack([m,n]))
print(np.hstack([m,o,n]))

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]
[[ 0  1  2 20 21 22 10 11 12]
 [ 3  4  5 23 24 25 13 14 15]]


## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

## hsplit()/vsplit()